### ISSUE TITLE
Small gap after the wave

### ISSUE THREAD

**Issue by KonerDev** [woofers/react-wavify#108]
After the wave is a small gap. How can you remove the gap?

![image](https://github.com/woofers/react-wavify/assets/105141148/6f9251bb-5013-40fd-bcfd-f6bc072bc18c)

**Comment by woofers** [comment]
@TheNicestDev 

This is from the `display: inline-block` style on the outer `div` which allows whitespace characters to make spaces.  Not sure why it was done this way initially but I don't want to cause a breaking v2 change by updating this.

To remove it, just add `style={{ lineHeight: 0 }}` or `style={{ display: 'flex' }}` to the Wavify component.

```tsx
import React from 'react'
import Wave from 'react-wavify'

const App = () => (
  <Wave fill='#f79902'
        style={{ lineHeight: 0 }}
        paused={false}
        options={{
          height: 20,
          amplitude: 20,
          speed: 0.15,
          points: 3
        }}
  />
)
```

Let me know if that solves your issue and I'll close this out.

**Comment by KonerDev** [comment]
Thanks, the `style={{ lineHeight: 0 }}` didn't work, but `style={{ display: 'flex' }}` did.
