### ISSUE TITLE
question about the wave

### ISSUE THREAD

**Issue by KIZAFOX** [woofers/react-wavify#109]
Hello I have a question how I could put the wave at the bottom of my page because as you can see on my screen there is a space between the wave and the bottom of my page.

Thanks.

![image](https://github.com/woofers/react-wavify/assets/38648943/ec298917-a32c-4ffe-8ce7-9168657f0fc3)

**Comment by woofers** [comment]
Hi @KIZAFOX, please see the related issue here and let me know if adding these style attributes resolve your issue: https://github.com/woofers/react-wavify/issues/108#issuecomment-1640724150

**Comment by KIZAFOX** [comment]
Hi @woofers,

Yes all is good thanks !
