### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by raul364** [woofers/react-wavify#113]
Hello, i'm trying to apply your library to my react mobile app. When i apply the example code in various ways to make it work, i get this error : Invariant Violation: View config getter callback for component `path` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This is the code:
import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet } from 'react-native';
import Wave from 'react-wavify'
function HomepageScreen({ navigation }) {
  return (
    <View style={styles.container}>
      <Wave fill='#f79902'
        paused={false}
        style={{ display: 'flex' }}
        options={{
          height: 20,
          amplitude: 20,
          speed: 0.15,
          points: 3
        }}></Wave>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#333',
    padding: 20,
    justifyContent: 'center',
  },
  title: {
    fontSize: 36,
    marginBottom: 20,
    textAlign: 'center',
  },
});

export default HomepageScreen;

The only way i don't get an error is if i don't have a return. but then i don't see the wave on my screen

**Comment by woofers** [comment]
Hi @raul364,

Looks like your trying to use `react-wavify` in React Native.  `react-wavify` relies on browser APIs like `requestAnimationFrame` and is only designed to work with React DOM / in web.

However contributions / PRs to port this library to work with React Native would be welcome, however there are currently no immediate plans for this. 

As a result I'm going to close this issue.
