### ISSUE TITLE
View config getter callback for component `path` 

### ISSUE THREAD

**Issue by husseinpenart** [woofers/react-wavify#117]
react native wavify give following error Invariant Violation: View config getter callback for component `path` must be a function (received `undefined`). Make sure to start component names with a capital letter.

**Comment by woofers** [comment]
Hi @husseinpenart,

Looks like your trying to use react-wavify in React Native. react-wavify relies on browser APIs like requestAnimationFrame and is only designed to work with React DOM / in web.

However contributions / PRs to port this library to work with React Native would be welcome, however there are currently no immediate plans for this.

As a result I'm going to close this issue.
