### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by therajuahammad** [woofers/react-wavify#73]
![image](https://user-images.githubusercontent.com/25717712/83352359-a350d300-a36c-11ea-8d2b-44c071383845.png)

![image](https://user-images.githubusercontent.com/25717712/83352416-fe82c580-a36c-11ea-9f12-27f93489d5ea.png)

> ./node_modules/react-wavify/lib/react-wavify.min.js
> Module not found: Can't resolve 'R:\projects\brook-react\node_modules\babel-loader\lib\index.js' in 'R:\projects\brook-react'

**Comment by woofers** [comment]
Hi @rajuahammadfans, I have not encountered this before, thanks for reporting the issue.

However it looks like it is looking for `babel-loader`.

Try adding it with `npm i babel-loader`.  Please let me know if you ecounter any other issues after this.

**Comment by therajuahammad** [comment]
@woofers thanks for your reply. It's working after the remove node_modules folder and reinstalls.
